### ISSUE TITLE
[PORT] Stremio

### ISSUE THREAD

**Issue by VicDino** [webosbrew/apps-repo#108]
### Conditions for submitting an app idea

- [X] I have read and agree to the conditions above
- [ ] I would like to port this app myself

### Describe the app to port

Port from the Stremio APP

https://www.stremio.com/downloads

**Comment by reisxd** [comment]
[Stremio is now available on LG TVs for models 2020+](https://blog.stremio.com/stremio-is-now-available-on-lg-tvs-for-models-2020/)
