### ISSUE TITLE
broken config in RetroArch

### ISSUE THREAD

**Issue by bedenko** [webosbrew/apps-repo#11]
There is a issue with RetroArch installation. Default "cores url" found [here](https://github.com/webosbrew/RetroArch/blob/635ac2127f364a81e9639dc06357b5f3d6f1ec49/config.def.h#L1378) is linked to unavailable (forbidden) URL.

**Comment by Informatic** [comment]
Sorry for such a late reply.
I *think* if you connected a USB drive to the TV and make `.config` (in its default location) a symlink to a proper system path (eg. pendrive is mounted at `/tmp/usb/sda/sda1` on my TV, you can check it by looking at `mount | grep -i sda`) it should work.

**Comment by Informatic** [comment]
That seems to work for me:
```
mv /media/developer/apps/usr/palm/applications/com.retroarch/.config /tmp/usb/sda/sda1/retroarch-data
ln -s /tmp/usb/sda/sda1/retroarch-data /media/developer/apps/usr/palm/applications/com.retroarch/.config
```

**Comment by bedenko** [comment]
Excellent! 
It works flawlessly.
