### ISSUE TITLE
I can't find RetroArch among apps

### ISSUE THREAD

**Issue by itsRealM12C** [webosbrew/apps-repo#110]
### Conditions for submitting an app idea

- [X] I have read and agree to the conditions above
- [ ] I would like to develop this app myself

### Describe your app idea

NES Emulator with tons of games including: Super Mario Bros. with cheats.

**Comment by kitsuned** [comment]
https://repo.webosbrew.org/apps/com.retroarch

**Comment by itsRealM12C** [comment]
sorry bro. i use retroarch now. A months ago it said "premission denied" for adding .nes files for it.
