### ISSUE TITLE
[IDEA] NES Emulator

### ISSUE THREAD

**Issue by itsRealM12C** [webosbrew/apps-repo#111]
### Conditions for submitting an app idea

- [X] I have read and agree to the conditions above
- [ ] I would like to develop this app myself

### Describe your app idea

No. Not Retroarch. I need the brand new application to submit is NES Emulator with tons of games including Super Mario Bros with cheats. I'm not talking about the Retroarch, i'm talking about the NES Emulator. Please, develop the NES Emulator app and submit it to Homebrew Channel as soon as possible. I'm gonna test it if it works very well.

**Comment by mariotaku** [comment]
This is your first warning. Don't submit repeated issues. #110

**Comment by itsRealM12C** [comment]
ok im sorry

**Comment by itsRealM12C** [comment]
If i am getting first warning, then stop doing this...
