### ISSUE TITLE
[IDEA] Key rebinding tool

### ISSUE THREAD

**Issue by Informatic** [webosbrew/apps-repo#28]
Please read conditions below carefully, and don't delete this part. Invalid issues will be closed.

* No apps related to piracy or intellectual property infringement is allowed.
* We can't guarantee if the app will be developed by anyone.
* We encourage you to develop the app by yourself. This would be a great contribution to webOS homebrew community.

- [x] I understand conditions above
- [ ] (Optional) I'd like to develop this app by myself

*Issue content starts below this line*

---

This should be achievable by injecting into `lginput2` and replacing `lginput_uinput_send_button`. Option to switch keys around, or execute a specific command / launch specific app would be great.

Update: lginput2 only handles magic remotes

* Magic Remote (mrcu)
  * `lginput2` → `lginput_uinput_send_button`
* IR Remote (via micom)
  * webOS 3.x-4.x → `RELEASE`/`tvservice` → `MICOM_UINPUT_WriteEvent`
  * webOS 5.x+ → `micomservice` → `_MicomHandler_Write_KeyEvent`

**Comment by Phunky** [comment]
I would love something like this! I've bought a replacement magic remote for my 55" LG G9 but the Disney+, Google and Alexa buttons don't seem to work :(

**Comment by Informatic** [comment]
https://github.com/Simon34545/lginputhook implements this.
