### ISSUE TITLE
[PORT] Xbox Gamestreaming client

### ISSUE THREAD

**Issue by tuxuser** [webosbrew/apps-repo#40]
Please read conditions below carefully, and don't delete this part. Invalid issues will be closed.

* No apps related to piracy or intellectual property infringement is allowed.
* We can't guarantee if the app will be ported by anyone.
* We encourage you to port the app by yourself. This would be a great contribution to webOS homebrew community.

- [x] I understand conditions above
- [ ] (Optional) I'd like to port this app by myself

*Issue content starts below this line*

----

Xbox Gamestreaming enables to play games streamed from the cloud (requires Xbox Game Pass Ultimate membership).

Maybe something based on this library could be ported:

https://github.com/unknownskl/xbox-xcloud-player

Electron app making use of the library:

https://github.com/unknownskl/xbox-xcloud-client

**Comment by mariotaku** [comment]
Interesting idea. While the JS lib uses WASM which does not support on many webOS versions, we can clearly make some native app to stream the game.

**Comment by mariotaku** [comment]
Some resources: 

XGP library API: https://github.com/pazguille/xbox-games-api
How to process streaming data: https://github.com/unknownskl/xbox-xcloud-client/wiki

**Comment by mariotaku** [comment]
I have done some researches and now I have a conclusion: this is totally doable, let's see if community needs this app.

**Comment by lazmo88** [comment]
This would definitely be a welcomed addition!

**Comment by hectorevil** [comment]
Need this app. Thanks

**Comment by redphx** [comment]
I created one #109
