### ISSUE TITLE
[PORT] Steam Link

### ISSUE THREAD

**Issue by w33w00** [webosbrew/apps-repo#42]
Please read conditions below carefully, and don't delete this part. Invalid issues will be closed.

* No apps related to piracy or intellectual property infringement is allowed.
* We can't guarantee if the app will be ported by anyone.
* We encourage you to port the app by yourself. This would be a great contribution to webOS homebrew community.

- [X] I understand conditions above
- [ ] (Optional) I'd like to port this app by myself

*Issue content starts below this line*

---

Hi all, long time follower and first time poster (just created my account for this!)

Is Steam Link a possibility to get ported to WebOS?  Moonlight is great and all for NVIDIA gamets, but us AMD boys are SOL in this department!  

Steam Link is awesome to bring in other games (not purchased on Steam) on your PC to be played through Steam Link as well.  This could be very fruitful I reckon.

Thank you!

**Comment by mariotaku** [comment]
Nice suggestion! Although there's not much progress to reverse engineer steam link API. 

Have you tried Sunshine? It's a host software to let people use Moonlight without NVIDIA GPU.

**Comment by mariotaku** [comment]
I'll do this. Reverse engineering has been started and it went quite well.

**Comment by mariotaku** [comment]
Ongoing development: https://github.com/mariotaku/ihsplay
