### ISSUE TITLE
[BUG] App submission validation step (linting) fails if PR comes from external fork

### ISSUE THREAD

**Issue by tuxuser** [webosbrew/apps-repo#55]
# Bug / Problem
Github workflow "app-submissions.yml" is responsible for ensuring integrity of the incoming app-submission:
- json manifest correct
- checking compatibility of native apps with different WebOS versions

As part of this checking, the workflow will attempt to post a report to the respective Pull Request discussion. [example](https://github.com/webosbrew/apps-repo/pull/48#issuecomment-1019818018)

For updating a PR from a workflow, write permissions are necessary.
Write permissions are automatically given for internal PRs, e.g. branches of the main repo.
For external forks these permissions are not given.

## Attempted steps to fix the issue

- Updated `actions/github-script` from `v5` to `v6`
- Explicitly set `permissions, pull-requests: write` for the `app-lint` CI job
- Ensured correct permissions for PRs of this repo (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- Attempted to set workflow trigger to `pull_request_target` instead of `pull_request`... but as the name suggests, this will run the workflow on the target of the PR, not on the to-be-merged codebase, e.g. the incoming change cannot be linted.

See: (https://github.com/webosbrew/apps-repo/commit/2342301b206313f0976d0c5f5be630b4fbc2ac7e)

Issue on the `actions/github-script` repo: (https://github.com/actions/github-script/issues/42)

## Current behaviour
App linting step fails with the following error when attempting to post a message to the PR discussion:

`Resource not accessible by integration`

## Expected behaviour
PR gets properly updated with the "app lint" compatibility card.

![Screenshot from 2022-04-22 13-45-22](https://user-images.githubusercontent.com/462620/164708436-18094b23-acfe-4c4f-8851-7507fee3c6dc.png)

**Comment by mariotaku** [comment]
Should be fixed now. Do you want to give it a shot?

**Comment by tuxuser** [comment]
Indeed it does :)
