### ISSUE TITLE
i kindly request to add kodi application to the store 

### ISSUE THREAD

**Issue by Tiwana12** [webosbrew/apps-repo#67]
i kindly request  to add kodi to the store
this is the playstore link
https://play.google.com/store/apps/details?id=org.xbmc.kodi&hl=it&gl=US

**Comment by memerememe** [comment]
A stremio port would also be appreciated since both are similar..

**Comment by mariotaku** [comment]
Someone has started development. Stay tuned!

**Comment by memerememe** [comment]
Woah, thanks for the update!

**Comment by memerememe** [comment]
@mariotaku Is there anywhere we can check out the development? A github repo or a website perhaps?

**Comment by mariotaku** [comment]
@memerememe I remember I sent you the link but it turns out it's missing in my draft, sorry.
You can see the development status in [this fork repo](https://github.com/webosbrew/xbmc), and I believe the snapshot is in [kodi's jenkin server](https://jenkins.kodi.tv/job/webos-docker/), although things may break so you'd better wait till some official annoucements.

**Comment by mariotaku** [comment]
I'll be closing this issue as it's realized, please tracking development status in the links above, and kudos to awesome engineers working on this!

**Comment by Informatic** [comment]
https://github.com/xbmc/xbmc/pull/23092 Here's a PR in Kodi/XBMC involving hardware video decoding on webOS 5.x. 

webOS 3.x-4.x requires additional set of changes to work (which is already kind of working in [my fork too](https://github.com/Informatic/xbmc/commits/acb-rebased), but will be filed whenever that PR gets merged)

**Comment by Dis90** [comment]
@Informatic Can you share .ipk for WebOS 4 or is it too broken to be used? :D I would like to test that because currently available versions doesn't even start on my tv.

**Comment by wsnipex** [comment]
since the OP asked for inclusion in the webosbrew repo, what do you need to do to actually include kodi?

**Comment by mariotaku** [comment]
@wsnipex As long as there is a way to fetch the newest available IPK file to download, it can be added to the repo.

**Comment by wsnipex** [comment]
ok, that won't be a problem. There won't be an official final release until kodi v21, but there will be nightlies in the meantime

**Comment by mariotaku** [comment]
@wsnipex Please let me know when nightlies are usable enough, and I'll publish it to the channel.

**Comment by memerememe** [comment]
hey there, @mariotaku , i just tried installing the kodi snapshot from the kodi jenkin url you [provided,](https://jenkins.kodi.tv/job/webos-docker/) and it seems to crash, not getting past the startup logo . is this normal behaviour?

**Comment by memerememe** [comment]
@mariotaku ah, i see.. thanks for the quick reply btw!! i noticed @Informatic has a fork, with changes that, might work on webos 3, but cant figure out how to build it.. Do i just run the "build-webos.sh" file and i'll get a ipk?

**Comment by mariotaku** [comment]
@memerememe I would give it more time till everything gets merged to the official repo.

**Comment by memerememe** [comment]
> @memerememe I would give it more time till everything gets merged to the official repo.

alright, will do
