### ISSUE TITLE
Stremio app

### ISSUE THREAD

**Issue by SouoLK** [webosbrew/apps-repo#93]
### **Stremio is a modern media center that's a one-stop solution for your video entertainment. You discover, watch and organize video content from easy to install addons.** 
[Stremio.json](https://github.com/webosbrew/apps-repo/files/13467686/Stremio.json)

# Display name of your application
title: Stremio
# Publicly accesible HTTP/HTTPS URL, or data uri to icon image.
iconUri: https://github.com/Stremio/stremio-web/blob/development/images/icon_x192.png
# Publicly accessible manifest file of your application
manifestUrl: https://github.com/Stremio/stremio-web/blob/development/manifest.json
# Category for your application
category: Streaming
# If this is an open source application, use main, otherwise non-free
pool: main
# Long description for your application, in Markdown format
description: |
  Stremio is a modern media center that's a one-stop solution for your video entertainment. You discover, watch and organize video content from easy to install addons.
# Sponsor information, like .github/FUNDING.yml
funding: https://github.com/Stremio/stremio-web/tree/development,yml
  github: [ SouoLK ]

**Comment by throwaway96** [comment]
I don't understand. Where's the IPK? Have they added webOS support?

**Comment by kubo6472** [comment]
Can be closed in favor of #83
